### ISSUE TITLE
Torchvision is required

### ISSUE THREAD

**Issue by awebeer256** [hzwer/Practical-RIFE#14]
Upon running it for the first time, I got
```
Please download our model from model list
Traceback (most recent call last):
  File "[snip]/Practical-RIFE/inference_video.py", line 96, in <module>
    model = Model()
NameError: name 'Model' is not defined
```
I had installed a model. When I ran the line in IDLE:
```
>>> from train_log.RIFE_HDv3 import Model
    Traceback (most recent call last):
      File "/usr/lib64/python3.10/idlelib/run.py", line 578, in runcode
        exec(code, self.locals)
      File "<pyshell#2>", line 1, in <module>
      File "[snip]/repos/Practical-RIFE/train_log/RIFE_HDv3.py", line 11, in <module>
        from model.loss import *
      File "[snip]/repos/Practical-RIFE/model/loss.py", line 5, in <module>
        import torchvision.models as models
    ModuleNotFoundError: No module named 'torchvision'
>>>
```
I ran `pip install torchvision` and tried again, and it worked.
I'm guessing this means that `torchvision` should be added to `requirements.txt`.

**Comment by hzwer** [comment]
Fixed, thanks!

**Comment by jujpenabe** [comment]
It has to be torchvision 0.7.0 (requeriments.txt) or i can use the latest version?

**Comment by hzwer** [comment]
@jujpenabe I think latest torch and torchvision should be acceptable. Maybe you will see a lot of warning.
