### ISSUE TITLE
inference_video_enhance.py ends with error: "NameError: name 'Model' is not defined"

### ISSUE THREAD

**Issue by marchcat69** [hzwer/Practical-RIFE#82]
I'm trying to encance the video using script "python3 inference_video_enhance.py --video=input.mp4", as described in the example, and I get the error: "NameError: name 'Model' is not defined". I downloaded the SAFA model from Google drive and placed it in folder "train_log_SAFA". "python3 inference_video_enhance.py --video=input.mp4 --model train_log_SAFA" gives the same error. What am I doing wrong?

Console logs:
Please download our model from model list
Traceback (most recent call last):
  File "/root/1data/apps/local/Practical-RIFE/inference_video_enhance.py", line 83, in <module>
    model = Model()
            ^^^^^
NameError: name 'Model' is not defined

**Comment by 2994dd42d75b0** [comment]
in trainlog SADA path is not given properly IDK but just place "train_log" and "train_log_SAFA" in same location and it will work

**Comment by 2994dd42d75b0** [comment]
in py files in trainlog Instead of 
from train_log. it should be from train_log_SAFA.

**Comment by marchcat69** [comment]
> in trainlog SADA path is not given properly IDK but just use --model train_log without renaming to train_log_SAFA folder

I put the downloaded model in the "train_log" folder. Unfortunately, it's gives the same error:

python3 inference_video_enhance.py --video=input.mp4 --model train_log
Please download our model from model list
Traceback (most recent call last):
  File "/root/1data/apps/local/Practical-RIFE/inference_video_enhance.py", line 83, in <module>
    model = Model()
            ^^^^^
NameError: name 'Model' is not defined

**Comment by Vrepol** [comment]
You can creat a folder named as "train_log_SAFA"  replace the "train_log" in SAFA_enhance_v0.5.zip,
then revise the inference_video_enhance.py, 
add "from train_log_SAFA.model import Model"
