### ISSUE TITLE
 np.float

### ISSUE THREAD

**Issue by Qinolion** [hzwer/Practical-RIFE#89]
Traceback (most recent call last):
  File "/host/home/yanai-lab/Sotsuken24/xiong-p/test/Practical-RIFE/inference_video.py", line 115, in <module>
    lastframe = next(videogen)
                ^^^^^^^^^^^^^^
  File "/home/yanai-lab/xiong-p/miniconda3/envs/RIFE/lib/python3.11/site-packages/skvideo/io/io.py", line 251, in vreader
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yanai-lab/xiong-p/miniconda3/envs/RIFE/lib/python3.11/site-packages/skvideo/io/ffmpeg.py", line 103, in __init__
    self.inputfps = np.float(parts[0])/np.float(parts[1])
                    ^^^^^^^^
  File "/home/yanai-lab/xiong-p/miniconda3/envs/RIFE/lib/python3.11/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'cfloat'?

**Comment by NevermindNilas** [comment]
Not sure but a quick google search says that the last known version with np.float seems to be 1.22.0

I'd first do a:
`pip uninstall numpy -y`
Just to get rid of the current numpy install.

Then I'd try this.
`pip install numpy==1.22.0`
